---
abstract: 'comma-separated values manipulator (using XS or PurePerl)'
author:
  - 'Makamaka Hannyaharamitu, E<lt>makamaka[at]cpan.orgE<gt>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-CSV
no_index:
  directory:
    - t
    - inc
recommends:
  Text::CSV_XS: '1.46'
requires:
  IO::Handle: '0'
  Test::Harness: '0'
  Test::More: '0.71'
  perl: '5.006001'
resources:
  bugtracker: https://github.com/makamaka/Text-CSV/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/makamaka/Text-CSV
version: '2.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
